trigger:
  branches:
    include:
      - master

pr: none


pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm i -g yarn
    yarn install
    yarn build
  displayName: 'yarn install and build'

- task: PowerShell@2
  displayName: 'Push Changes'
  env:
    GitHub_PAT: $(GitHub_PAT)
  inputs:
    targetType: 'inline'
    pwsh: true
    script: 'cd dist;
    $ErrorActionPreference = "Stop";
    git init;
    git config --local user.name "Matteias Collet";
    git config --local user.email "matteias.collet@bluewin.ch";
    git add .;
    git commit -m "CI Build [skip ci]";
    git push -qf $(GitHub_PAT) HEAD:gh-pages;'
    failOnStderr: true
    workingDirectory: '.'
  condition: succeeded()
